version: "3.9"
services:
  seguridad:
    build: ./microservicio-seguridad
    container_name: seguridad_service
    ports:
      - "4000:4000"
    env_file:
      - .env
    networks:
      - backend_net

  clientes:
    build: ./microservicio-clientes
    container_name: clientes_service
    ports:
      - "5000:5000"
    env_file:
      - .env
    networks:
      - backend_net
    depends_on:
      - seguridad
      - redis
      - rabbitmq

  correos:
    build: ./microservicio-correos
    container_name: correos_service
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - backend_net
    depends_on:
      - rabbitmq

  redis:
    image: redis
    container_name: redis_service
    ports:
      - "6379:6379"
    networks:
      - backend_net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_service
    ports:
      - "5672:5672"   # comunicación entre microservicios
      - "15672:15672" # dashboard web propio de rabbit
    networks:
      - backend_net

networks:
  backend_net:
    driver: bridge
